### ISSUE TITLE
Calling the Touch ID window in development mode

### ISSUE THREAD

**Issue by doroved** [cbyrneee/localauthentication-rs#2]
During tests, when I apply the wrong finger, after about 10 tries, the macbook stops bringing up the Touch ID window when I run the script. How to remove this temporary block? Because during development I will often have to invoke the Touch ID window for tests.

**Comment by caoimhebyrne** [comment]
This is a system limitation, there's nothing we can do about that (even in native Swift apps) unfortunately.
